spring:
  application:
    name: blog-search-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

blog-search-service:
  sources:
    kakao:
      api-key: ceb88ad05ae91a5124d590e7d1e89814
      url: https://dapi.kakao.com/v2/search/blog
