spring:
  application:
    name: blog-search-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog-search-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      username: blog-search-service
      password: ItsMe135!
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

blog-search-service:
  sources:
    kakao:
      api-key: ceb88ad05ae91a5124d590e7d1e89814
      url: https://dapi.kakao.com/v2/search/blog
